// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { TopNtopNnGetData, TopNtopNnGetResponse, RootGetResponse, SayHelloHelloNameGetData, SayHelloHelloNameGetResponse } from './types.gen';

/**
 * Top N
 * @param data The data for the request.
 * @param data.n
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const topNTopNNGet = (data: TopNtopNnGetData): CancelablePromise<TopNtopNnGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/top-n/{n}',
    path: {
        n: data.n
    },
    errors: {
        422: 'Validation Error'
    }
}); };

/**
 * Root
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const rootGet = (): CancelablePromise<RootGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/'
}); };

/**
 * Say Hello
 * @param data The data for the request.
 * @param data.name
 * @returns unknown Successful Response
 * @throws ApiError
 */
export const sayHelloHelloNameGet = (data: SayHelloHelloNameGetData): CancelablePromise<SayHelloHelloNameGetResponse> => { return __request(OpenAPI, {
    method: 'GET',
    url: '/hello/{name}',
    path: {
        name: data.name
    },
    errors: {
        422: 'Validation Error'
    }
}); };