// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type TopNtopNnGetData = {
    n: number;
};

export type TopNtopNnGetResponse = unknown;

export type RootGetResponse = unknown;

export type SayHelloHelloNameGetData = {
    name: string;
};

export type SayHelloHelloNameGetResponse = unknown;

export type $OpenApiTs = {
    '/top-n/{n}': {
        get: {
            req: TopNtopNnGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/hello/{name}': {
        get: {
            req: SayHelloHelloNameGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};